#!/bin/bash

SYSTEM_PART="$1"

echo "Pipeline 2 not working correctly you say? Ok, I'll restart it..."

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd "$DIR"
NO_MESSAGES=1 ./pipeline-stop "$SYSTEM_PART"
NO_MESSAGES=1 ./pipeline-start "$SYSTEM_PART"

echo "Ok, I'm done. Let's hope that did the trick..."

exit 0
